### PR TITLE
Fixes #1851: check some limits when converting smi to sdf using --gen2D

### LINKED ISSUE #1851: segmentation fault when converting smi to sdf using --gen2D
## Environment Information
Open Babel version: 2.4.1
Operating system and version: OS X El Capitan (10.11.6) and CentOs v3.10.0

Below are some example SMILES entries from a public database that cause segmentation faults when converted to SDF.  These all have a common core ring structure that may be causing issues.  None of the other 5M+ structures evaluated caused segmentation faults.

O=C(C1=CN=CS1)N1C2CCC1CN(CC1CC3CCC1O3)C2
O=C(CC1CC1)N1C2CCC1CC(NC(=O)C13CCC(CC1)CC3)C2
O=C([C@@H]1C[C@H]1C1CCC1)N1C2CCC1CN(C(=O)C13CCN(CC1)C3)C2
O=C(CCN1C=CN=C1)N1C2CCC1CN(CC1CC3CCC1C3)C2

example command: `babel input.smi --gen2D output.sdf`

### PR DESCRIPTION
**Pull request by serval2412**
See bts:
https://github.com/openbabel/openbabel/files/2081924/bt.txt
https://github.com/openbabel/openbabel/files/2082051/bt1.txt

### CODE REVIEW

**Comment by serval2412** [comment]
Just wonder if I should change
   2613           for (j=0; j<nb; j++) {
which corresponds to case 4.

**Comment by serval2412** [comment]
Just for information with the patch, I got this:
2 molecules converted
1 info messages 34 audit log messages

File: src/mcdlutil.cpp [hunk 1]
```diff
@@ -2569,7 +2569,7 @@ namespace OpenBabel {
               uy1=getAtom(dsNA1[i])->ry-uy;
               //coordinates of all atoms for the cycle under study are calculated}
 
-              for (j=0; j<nb; j++) {
+              for (j=0; j<nb-1; j++) {
```
Comment (fredrikw) [inline src/mcdlutil.cpp]: This change seems to be the one responsible for the regression reported in #1900 but without it, example 3 from the bug report (#1851), i.e. `O=C([C@@H]1C[C@H]1C1CCC1)N1C2CCC1CN(C(=O)C13CCN(CC1)C3)C2`,  gives an exception.
